### ISSUE TITLE
angular.json could not be found

### ISSUE THREAD

**Issue by jlarroque** [igorkosandyak/angular2-websokets#2]
I downloaded the frontend code, but when I did "ng serve", it says that can't find "angular.json":

Local workspace file ('angular.json') could not be found.
Error: Local workspace file ('angular.json') could not be found.
    at WorkspaceLoader._getProjectWorkspaceFilePath (C:\Users\username\AppData\Roaming\npm\node_modules\@angular\cli\models\workspace-loader.js:44:19)
    at WorkspaceLoader.loadWorkspace (C:\Users\username\AppData\Roaming\npm\node_modules\@angular\cli\models\workspace-loader.js:31:21)
    at ServeCommand._loadWorkspaceAndArchitect (C:\Users\username\AppData\Roaming\npm\node_modules\@angular\cli\models\architect-command.js:189:32)
    at ServeCommand.<anonymous> (C:\Users\username\AppData\Roaming\npm\node_modules\@angular\cli\models\architect-command.js:55:25)
    at Generator.next (<anonymous>)
    at C:\Users\username\AppData\Roaming\npm\node_modules\@angular\cli\models\architect-command.js:14:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\username\AppData\Roaming\npm\node_modules\@angular\cli\models\architect-command.js:10:12)
    at ServeCommand.initialize (C:\Users\username\AppData\Roaming\npm\node_modules\@angular\cli\models\architect-command.js:54:16)
    at Object.<anonymous> (C:\Users\username\AppData\Roaming\npm\node_modules\@angular\cli\models\command-runner.js:101:23)

**Comment by igorkosandyak** [comment]
Try to run npm install before ng serve

Thank you!

пн, 17 вер. 2018 о 15:36 jlarroque <notifications@github.com> пише:

**Comment by igorkosandyak** [comment]
Please, take a look here. Maybe this could solve the issue:
https://filipmolcik.com/error-local-workspace-file-angular-json-could-not-be-found/
